### ISSUE TITLE
The name is not unique 

### ISSUE THREAD

**Issue by lioTauhid** [lioTauhid/QBangla-Dictionary#3]
Need to rebrand with unique and nice name

**Comment by lioTauhid** [comment]
As we see from our telegram group members, They choose 4 name

- QBangla Dictionary
- AmarBangla Dictionary
- Bongokosh Dictionary
- Ovidhan

**Comment by lioTauhid** [comment]
Group member selected, QBangla Dictionary is the final name for the app @fazlerabbi37 @imahbub

**Comment by imahbub** [comment]
Epic! We can make a new logo for it.
